### ISSUE TITLE
File sorting

### ISSUE THREAD

**Issue by Brle88** [talvbansal/media-manager#19]
Hi there, 

I'd like to propose a new and really helpful feature - file sort by name or date. Also, in case I've got 5000 files, they are all loaded and reloaded after each upload at once, so maybe some sort of pagination would be also useful.

I've made a news website, using the canvas platform, http://globalnews.sk. I needed the original file names, for seo purposes, and now, when someone uploads an image, the have to remember the file name, and search in thousands of images the file they have uploaded :/ so.. 

I've tried to edit the vue component to sort files by date created, and display the last added file at top, but I didn't know how to do this. Changes I've made in the vue file, didn't show in frontend - I'm guessing they have to be republished, just not sure, how to do this..

**Comment by talvbansal** [comment]
@Brle88 thanks for raising this, I've not myself yet got to the point where i have that volume of images to see what the performance is like but i was thinking of adding a search bar to help filter the files in the current directory.

In order to help you contribute to the UI section Ill start by explaining how I edit the media manager and see the changes working in a real project. I don't actually develop it along side canvas but ill try and make this applicable for a canvas install to help you out:

- In your project `composer.json` look for or create a `config` section and update the `preferred-install` value to `source` and set the `minimum-stability` to `dev`:
```
  "config" : {
    "preferred-install" : "source"
  },
  "minimum-stability": "dev"
```
- Set the media manager version to master : `"talvbansal/media-manager": "dev-master"`
- Remove your vendor folder and run `composer update`. This will bring down all of the project dependencies with all of the source information.
- Change the path in `gulpfile.js` from `../talvbansal/media-manager/js/media-manager.js` to `./../../../vendor/talvbansal/media-manager/public/js/media-manager`
- Within your project folder `cd ./vendor/talvbansal/media-manager` and run `gulp watch`
- On a separate terminal within your project folder run `gulp watch` 
- You can now edit all of the files within `/vendor/talvbansal/media-manager` and with both of the gulp watchers running changes to the vue files will be reflected within the canvas install. 

Hope that helps and I can't wait to see what you have in store!

**Comment by talvbansal** [comment]
Added to the latest master build :)
