### ISSUE TITLE
Unknown Component

### ISSUE THREAD

**Issue by sicsol** [talvbansal/media-manager#25]
I've followed the instructions and when i'm loading the <media-manager> element i'm getting the following error from Vue.

`Unknown custom element: <media-manager>`

**Comment by talvbansal** [comment]
Hi  @sicsol, have you bundled your assets using something like `gulp`?

**Comment by sicsol** [comment]
Yes I have. I'm using a fresh install of Laravel as well. Also updated the blade file to reference app.js

**Comment by talvbansal** [comment]
@sicsol Thanks for the update, can you post your code so i can see exactly what you've done?

Can you also confirm which version of vue js you're using too please

Thanks

**Comment by Krato** [comment]
Also for me with a fresh Laravel 5.3 installation

This is my gulp file:

```js
const elixir = require('laravel-elixir');

require('laravel-elixir-vue-2');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(mix => {
    // mix.sass('app.scss')
       // .webpack('app.js');

     // Add additional styles...
    mix.sass([
        '../talvbansal/media-manager/css/media-manager.css',
        'app.scss'
    ]);

    // Add dependencies and components...
    mix.webpack([
        '../talvbansal/media-manager/js/media-manager.js',
        'app.js'
    ]);

    // Copy SVG images into the public directory...
    mix.copy( 'resources/assets/talvbansal/media-manager/fonts', 'public/fonts' );
});
```

And this is my blade:
```php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"></div>

                <div class="panel-body">
                    <media-manager></media-manager>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
```

I made gulp and everything. But console is giving me this:
`[Vue warn]: Unknown custom element: <mediamanager> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)`.

Thanks!

**Comment by talvbansal** [comment]
@Krato thanks for the update ill try exactly what you have there and report back asap!

**Comment by talvbansal** [comment]
@Krato @sicsol I've confirmed this as a bug! Thanks for your help if you can test the following I'll be able to update the documentation accordingly:

1. Make sure you have the following somewhere on your template before your JS files are included:
```js
    <!-- Laravel CSRF Token-->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
``` 

2. Instead of requiring the media manager js code in your gulp file remove it:
```js
    // Add dependencies and components...
    mix.webpack([
        '../talvbansal/media-manager/js/media-manager.js',
        'app.js'
    ]);
```
Goes back to:

```js
    // Add dependencies and components...
    mix.webpack([
        'app.js'
    ]);
```

And instead include the media-manager.js file within your app.js file before the Vue instance is created. So using a fresh Laravel install your `resources/assets/js/app.js` file would look like this:

```js
require('./bootstrap');
require('./../talvbansal/media-manager/js/media-manager');

Vue.component('example', require('./components/Example.vue'));

const app = new Vue({
    el: '#app'
});
```

3. Make sure there is an element with an ID of  `#app` within your template
4. Re-run gulp and you should see the media manager within your templates

Fingers crossed this should get you up and running.

Looking forward to hearing from you!

**Comment by Krato** [comment]
Thanks for your fast reply @talvbansal. But no luck.

I make `gulp`again, clear views, cache and config, with `artisan serve, without, and no luck yet.

Same error:

```js
[Vue warn]: Unknown custom element: <media-manager> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)
```

**Comment by talvbansal** [comment]
@Krato thanks, can you just confirm which js file you're using in your layout for me please. Ive just re run the process as above on another fresh laravel install and was able to get it working however:

laravel ships with `app.js` out of the box but it looks like when you run gulp a file called `all.js` so can you just check that that is the file being included instead of app.js?

**Comment by Krato** [comment]
Perfect. I include all.js instead app.js and now is working!

**Comment by talvbansal** [comment]
@Krato yay! I'll update the docs tonight! @sicsol Can you confirm that you're happy and close out the issue when you are please :)
