### ISSUE TITLE
Suggestion : One demo ?

### ISSUE THREAD

**Issue by partikule** [talvbansal/media-manager#80]
Did I miss the demo ?

**Comment by ruchern** [comment]
Dude, what do you mean? Please open a proper issue.

**Comment by partikule** [comment]
Can you provide one link to an online demo?

**Comment by talvbansal** [comment]
Hi @partikule thanks for looking at this project, there currently isn't an online demo of the media-manager but there is a repo that you can clone down to see how it works that has a fully working example here: https://github.com/talvbansal/media-manager-laravel-example

If i have time I'll try and get an online demo set up i just need to fine a way to limit resources being wasted and racking up since people would actually be uploading files to an actual server.

**Comment by partikule** [comment]
Thanks for your answer.

We finally installed one demo on one fresh Laravel.
